name: exercicio_seminarios
description: "Um projeto Flutter para os exercícios dos seminários."

# Previne publicação acidental em pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependências que seu aplicativo precisa para funcionar.
dependencies:
  flutter:
    sdk: flutter

  # Pacote para usar fontes do Google (Exercício 3).
  google_fonts: ^6.2.1

  # Pacote de ícones de estilo iOS.
  cupertino_icons: ^1.0.2

# Dependências usadas apenas durante o desenvolvimento.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # O pacote que está causando o erro no analysis_options.yaml.
  # Ele contém as regras de análise de código do Flutter.
  flutter_lints: ^3.0.0

# Configurações específicas do Flutter.
flutter:
  uses-material-design: true